onl: allow building more platforms
bisdn/meta-open-network-linux pull request #147
Opened 2024-01-19 13:11 UTC by KanjiMonster

To make it easier adding new platform support make it optional to build untested platforms (which are not included in the image).

This way these can be then installed on the device via opkg and and any further changes can be done on the device.

By default, do not build these platforms, but we may chose to do that for nightly builds.

2024-01-31 08:09 UTC, ideaship requested changes
This MR contains three commits with different subject matters, of which only one is mentioned in the PR description.

For the commit "onl: allow building more platforms", please add some documentation of how these new variables are meant to be used.

2024-01-31 09:50 UTC, KanjiMonster commented
> For the commit "onl: allow building more platforms", please add some documentation of how these new variables are meant to be used.

[`PACKAGECONFIG`](https://docs.yoctoproject.org/ref-manual/variables.html#term-PACKAGECONFIG) is a standard Yocto variable (name), I didn't expect to have to explain what this is or how to use it.

But if it makes you happy I can add the link to the docs in the commit.

2024-01-31 11:41 UTC, ideaship commented
I was hoping for something like: if you want to use this cool new feature, here's how you could do it. I like having such information in the commit message, even though there are other places for documentation. But maybe you are right. Everybody who can build BISDN Linux can figure this out.

2024-02-02 08:10 UTC, ideaship approved these changes

2024-02-02 08:10 UTC, merged