Add As4630 platform support
bisdn/meta-open-network-linux pull request #16
Opened 2021-11-17 14:11 UTC by rubensfig

This PR aims to add the necessary files to add support for the accton-as4630. More info in the individual commits

2021-11-17 16:28 UTC, KanjiMonster requested changes
In general the direction is fine.

Please use the same commit message prefix for all commits. Make sure the machine definition is last.

Also there are at least 4 open PRs at https://github.com/opencomputeproject/OpenNetworkLinux/pulls?q=is%3Apr+is%3Aopen+as4630 that look relevant, which we should have as well.

Ideally add each as an individual commit.

2021-11-17 16:28 UTC, KanjiMonster commented on conf/machine/accton-as4630-54pe.conf
> +BISDN_ONIE_PLATFORM = "x86_64-accton-as7726-r0"
```suggestion
BISDN_ONIE_PLATFORM = "x86_64-accton-as4630-54pe-r0"
```

2021-11-17 16:28 UTC, KanjiMonster commented on recipes-core/platform-as4630-54pe/files/platform-as4630-54pe-init.sh
> +done
You have overlapping ranges here; first ports 49 to 53, then ports 53 to 55.

2021-11-17 16:28 UTC, KanjiMonster commented on recipes-extended/onl/onl/0001-accton-as4630-54pe-silence-error.patch
> +---
Please sign off the patch as well.

2021-11-17 16:28 UTC, KanjiMonster commented on recipes-kernel/accton-as4630-54pe-leds-mod/accton-as4630-54pe-leds-mod.bb
> +SUMMARY = "This module supports cpld that read and write"
Different module.

2021-11-17 16:28 UTC, KanjiMonster commented on recipes-kernel/accton-as4630-54pe-psu-mod/accton-as4630-54pe-psu-mod.bb
> +SUMMARY = "This module supports cpld that read and write"
Different module.

2021-11-17 16:28 UTC, KanjiMonster commented on recipes-kernel/accton-as4630-54pe-cpld-mod/accton-as4630-54pe-cpld-mod.bb
> +SUMMARY = "This module supports cpld that read and write"
Maybe use a better summary, e.g. the first sentence in the comment block in the c file.

2021-11-17 16:28 UTC, KanjiMonster commented on recipes-kernel/accton-as4630-54pe-cpld-mod/accton-as4630-54pe-cpld-mod.bb
> +	  file://COPYING \
Please align the lines and check the other recipes for similar issues.

2021-12-01 09:45 UTC, KanjiMonster requested changes
Please add a bit more description of the as4630 in the PR.

Please apply all patches in onl that touch kernel drivers also to our copies.

Please make "onl: " the first prefix in commits touching (only) onl. If the commit also touches other parts in the tree, it's fine to not have that prefix.

2021-12-02 08:50 UTC, rubensfig commented on recipes-extended/onl/onl/0001-as4630-54pe-Fix-fan-LED-always-showing-fan-is-turned.patch
> ++++ b/packages/platforms/accton/x86-64/as4630-54pe/modules/builds/x86-64-accton-as4630-54pe-leds.c
I applied the patch in my personal tree, so the state reflected here already has the state attached.

But I agree, its clear to get the patch individually and apply it in the recipe

2021-12-08 16:26 UTC, KanjiMonster requested changes
Looks good in general, apart from the merge conflict remnants in https://github.com/bisdn/meta-open-network-linux/pull/16/commits/269ac3c623e66a5ddeaf7434ad366f3d0231288e in the commit message.

2021-12-10 13:08 UTC, KanjiMonster approved these changes

2021-12-10 13:08 UTC, merged